### ISSUE TITLE
teams#destroy destroys a team regardless if the deleting user owns that team

### ISSUE THREAD

**Issue by itiswicked** [codeforboston/cambridge_energy_app#100]
It looks like that action does not validate that a current_user has created a team before it is destroyed, so it looks like any user can destroy any team. Is this correct?

Should a team be created belonging to a user, and should a team only be destroyed by that creator?

**Comment by itiswicked** [comment]
Should a team be created belonging to a user, and should a team only be destroyed by that creator?

**Comment by mahtai** [comment]
I didn't really think of a user owning a team when I built the setup. I'm not really sure if it would be useful to have a team owner. 
I think we should make it so that the team only gets destroyed when everybody leaves, to prevent someone from destroying a team that the other members want to keep around.

**Comment by JerJohn15** [comment]
I'm running into a similar issue with the _Listing Bills_ section  any user, whether logged in or not, has the ability to "destroy" a bill. Also, people have the ability to view every bill created in the database. 

If you go to my [bug report issue](https://github.com/codeforboston/cambridge_energy_app/issues/102), you can see screenshots of both scenarios (see Issue#11).

**Comment by itiswicked** [comment]
@mahtai That's a great idea. I will rewrite the leaving a team action to destroy the team if the current member leaving is the only member. I'll take the destroy route out of the equation.

**Comment by itiswicked** [comment]
@mahtai Ah it looks like that you already implemented it. I see your comment on `teams#leaving`. What issues were you having? I was able to leave the team as the last member and it was successfully destroyed.

Other than getting rid of the destroy route and updating the test, what concerns exist for this issue at this point?

**Comment by mahtai** [comment]
Oh, I don't think there are any issues remaining with teams#leaving. I had some trouble for a bit, and then it seems to have resolved itself some time after I made the pull request. So that comment is ignorable. I think this issue can be closed, actually; I put in a bunch of authentication stuff in one of the current pull requests.

**Comment by itiswicked** [comment]
Cool, my new PR will be the deletion of the delete action and new test examples for teams#leaving
