### ISSUE TITLE
Scoring Logic

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#166]
We need to design and implement the scoring logic for the teams. This needs to be added to the appropriate views.

General idea: Teams will get points for the percentage decrease in energy usage they have over the previous month. We had some conversations about potential variations and ideally we'd have usage information from the previous year but that is not easy to do until we get Green Button access.

Teams should be ranked on a monthly basis and receive a monthly e-mail update or other notification.

**Comment by mzagaja** [comment]
Also even though I self-assigned this could be a beast of a task so I'm open to helpers.

**Comment by mahtai** [comment]
The current placeholder code computes for each user the difference between the previous month's and the current month's bill amounts, and then the team score is the average of its member's scores. 
This only works if the bills are coming in once a month, and also pays no attention to things like seasons. If the bills don't come in regularly, the user is assigned score 0, and that is reflected in the team score, which is why all the scores using the current fake data are generally 0.
We probably want to adjust it to be a percentage drop rather than overall magnitude, right?
We'd probably need someone with actual experience and/or data to deal with seasons because otherwise scores are going to tank during the winter.
The code for the scoring in the user model could definitely afford to be refactored.

**Comment by mzagaja** [comment]
Where did we put the placeholder code?

**Comment by mahtai** [comment]
It's in the user model.

**Comment by mahtai** [comment]
Should app participation things like profile completeness be added to the score? Or should the score be only bill-based?

**Comment by Pilafonta** [comment]
Do rates per kilowatt hour stay constant?
What percentage did bill decrease month to month?
(previous month- current month)/previous month

**Comment by mzagaja** [comment]
http://stackoverflow.com/questions/23617426/ruby-on-rails-calculate-rank is probably helpful for implementation

**Comment by mkazin** [comment]
Comparing month-to-month seems an unusual approach, as it introduces extra variables. Has using the current month's population-wide usage been considered as the basis against which to compare the individual?
