### ISSUE TITLE
Content and Implementation for Energy Saving Tips

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#168]
It'd be great if someone could take the general design pattern that I put in https://github.com/codeforboston/cambridge_energy_app/commit/6939c00aa45acb807032cc09acbd86161426545d and expand it so that a user receives a random tip in this box when they login. If you are feeling even more ambitious it'd be great if we could keep track of what tips a user says they have taken when they click a button so that we do not show them that tip anymore. And/or maybe it should be a voting tool where they can say "this worked for me" or "this didn't work for me" so we get a sense of what is working. I've attached sample content from the City of Cambridge we can use.
[Energy House Handout Final 8-25-15-1.pdf](https://github.com/codeforboston/cambridge_energy_app/files/267335/Energy.House.Handout.Final.8-25-15-1.pdf)

**Comment by mahtai** [comment]
Pull #185 puts in some implementation for tips. Still missing: sharing, periodic reminders. Also, how "daily" are these "tips of the day"? The current setup I have just grabs a random one each time because we get desync issues with the next-tip and don't-show-again options.
Possible future feature: currently, liked tips are still shown again; maybe don't show again only after sharing? Or should it simply not be shown again either way?
