### ISSUE TITLE
No route matches [GET] "/users/invitation/new"

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#295]
When trying to invite someone it does not work. This is likely due to the implementation of Pundit.

**Comment by FrankCardillo** [comment]
There was a test written for this feature, but whoever wrote it forgot to add _spec to the end of the file name and so it wasn't being run. Having not tried fixing this issue yet, this test (with _spec added to the end of the file) fails. I'm going to use git bisect now to try to find the point that the problem was introduced.

**Comment by FrankCardillo** [comment]
This is the commit that broke the feature. Investigating it now.

commit ada1426c2cf1a4cd583ecfaa00426fcf01cc20d5
Author: Zamith zamith.28@gmail.com
Date:   Wed Aug 3 15:34:50 2016 -0400

```
Corrects the order of the routes
```

**Comment by shauncarland-old-account** [comment]
@FrankCardillo was this ever fixed in master?  My feature branch is still failing on this test.
https://github.com/codeforboston/cambridge_energy_app/pull/315

**Comment by FrankCardillo** [comment]
@shauncarland I don't think this was fixed in master.
