### ISSUE TITLE
Add Weather Normalization to Personal Score Calculation

### ISSUE THREAD

**Issue by jtrshelley** [codeforboston/cambridge_energy_app#319]
Weather-normalizing:
xMonthHeatingAndCoolingDays = sumOverDaysMonth(abs(avgTemperature-65)). Source: [http://www.energysmart.enernoc.com/how-to-calculate-weather-normalized-energy-consumption-using-heating-and-cooling-degree-days/](url)

_Personal Score Calculation_
(lastMonth_kWh/lastMonthHeatingAndCoolingDays - thisMonth_kWh/thisMonthHeatingAndCoolingDays) / lastMonth_kWh/lastMonthHeatingAndCoolingDays ) \* 100

**Comment by jtrshelley** [comment]
Future things to think about: if it turns out that people generally are only able to reduce their scores by 1-2%, we might want to consider mapping changes from 0-100 later.

**Comment by mzagaja** [comment]
We talked about this today and realized that people are not paying for their heating in their electricity bills so we actually should not have to do this, at least not for winter. It might also be counterproductive to do it in the summer because we want to discourage people from overusing their AC so I think I'm going to close this for now.
