### ISSUE TITLE
Develop Model & DB Schema

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#5]
Edit: Apparently only one assignee can be added so I guess we can just @ people to loop them into the issue. But here is a place to discuss this.

**Comment by mzagaja** [comment]
@challyed Looping you in on this issue since I think you mentioned you wanted to help on this.

**Comment by mzagaja** [comment]
A few thoughts on this before I forget:
1. Initial capture probably includes an e-mail, address, and an initial energy usage reading.
2. We need to decide if we're going to ask people for energy usage daily or monthly or some other interval or multiple intervals. 
3. It might be a good idea to circle back with Seth & Josh about what data would be useful for them.
4. There are some existing data sets about properties at the City of Cambridge open data portal. Are we going to do JOINs and store local copies of relevant data somehow? Are we going to locally store some of these datasets and then do the joins in the DB? Are these sets complete or are they going to sometimes need the person to fill them out? If an external join is blank then how do we treat that?

**Comment by challyed** [comment]
1. Let me try to do  a mock up
2. At the moment, It would be simple to do it monthly because a user would get the bill once a month
3. E-mailed 
4. ¯_(ツ)_/¯

**Comment by challyed** [comment]
This is the email
Thanks for checking in. Can you clarify what you mean by “useful to you”? The energy billing data that would be available and useful to tenants and property managers are kWh of electricity and therms of natural gas, particularly if they could be attributed to particular sources within apartments (ie: electricity for a TV vs. refrigerator). We would also be interested in tracking this data. Then we had also talked about more qualitative data such as resident comfort which might be useful to property managers. Other data points could include energy-related measures that are taken in the building, though some of this may already be tracked by the Building Energy Use Reporting Ordinance or our Tax Assessors/Inspectional Services Division database.

Let me know if this helps answer your question or if I can clarify further. Also let me know if it would be helpful for me to try to come by the Code for Boston hack night tomorrow.

Thanks for your work on this!

**Comment by challyed** [comment]
How would be normalize this? @sonya 
![table at the moment](https://cloud.githubusercontent.com/assets/1944704/11518867/1cce45f6-9863-11e5-8498-0f48db9f80d4.png)

**Comment by mahtai** [comment]
User info: Email, street address (link to building), team ID, (optional: first, last)
Unit info: Building ID, sq footage, (various appliances)
Landlord info: Name, email, phone, mailing address
Building info: stuff in database, landlord ID
Team info: User IDs
Energy usage info: User ID, Team ID, Building ID, Date, energy usage

**Comment by sonya** [comment]
Thanks everyone for all the new info!

Based on the things people posted, I'm seeing two separate groups of data: user input, and stuff the city provides. Both have buildings, but I think matching them up will be quite messy initially so my thinking is to track them separately and figure out how to match things when we have some data (for example we might have a manually updated column in the user building that references the city building)

So below I'm starting mostly from @mahtai's model on the user side and a sketch of @challyed's feedback from the city side. I tried to provide explanations in places where I differ from @mahtai's model, but please question my opinions!

#### user provided data

users:
- email
- other authentication fields
- team id
- unit id (assumes user can only live in one unit -- is this fair?)

user entered buildings: (use Google's Geocoding API to normalize input)
- street address
- lat/lon

units:
- building id
- unit number
- square footage
- list of appliances

teams: (user id's don't need to be in here since users already reference team id's)
- name

daily energy records:
- date
- user id (multiple users can live in the same unit but they may have different opinions)
- comfort level (1-5 scale for too cold -> too hot)

monthly energy records:
- date
- unit id (each unit gets a single bill)
- usage (do we allow different units in here and have a separate column for what units they are? or do we have multiple columns or multiple tables?)

#### city provided data

city provided buildings:
- landlord
- assessors' data
- energy reporting info

landlords

[edit] updated geocoding info in user buildings

**Comment by mahtai** [comment]
Note: Green Button allows for energy usage data more frequently than monthly, and Seth said that they'd like more-often-than-monthly data if possible.
