### ISSUE TITLE
Leveling Up Our UI/UX Skills

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#7]
Irena (major apologies if I spelled this incorrectly or just failed to remember your name, please correct me since I'm pretty sure it's not 33eyes) is going to consult with some friends from NYC to potentially get us a UI/UX bootcamp over video chat and/or later review of the UI/UX of our app.

@WheresHJ do we have any CfB members that do UI/UX that might also be able to help us out with this component? This is a weakness in our current team skill set.

**Comment by challyed** [comment]
Product Hunt has a nice collection on UX Design: https://www.producthunt.com/@lordklevine/collections/ux-design

**Comment by 33eyes** [comment]
I am putting together some initial wireframes and storyboards of our app that capture the key/milestone features we have discussed so far. I plan to be done with those Fridayish, so people can use them as a guide for creating/adjusting views over the weekend. And I will try to get a brief critique of the initial wireframes from actual UX people on Fri/Sat, so that we can make some adjustments to views on Sun/Mon. If this plan for UX doesn't work for people who are putting together the views, please let me know.

**Comment by WheresHJ** [comment]
I'm happy to provide critique; apologies for missing this thread a few
weeks ago.

Harlan Weber
Designer | Researcher
http://www.hjweber.net

**Comment by 33eyes** [comment]
That's fantastic, thanks!!

**Comment by 33eyes** [comment]
I've put together a very schematic mock-up of sign-up and dashboard here: https://moqups.com/#!/edit/ariiigu@gmail.com/Jvsyllrt

I've left out lots of important things for now, like profiles and more in-depth set-up details, because I was aiming at the features we have listed in the 1st milestone. 
The mock-up I put together is just an illustration of the ideas we've discussed (or at least how I've heard them, please feel free to correct me if needed). I am not implying any color/shape/arrangement in it, nor is anything else set in stone in anyway. This is just an initial skeleton to get in shape (based on input from our UX/design experts) and use as a guide for Tuesday. I went with a browser UX mock-up, because I figured more things can go on a single screen there, compared to mobile, so it would be easier for demo purposes. I think for now it will suffice to illustrate the features we intend to have in the app, whether web or mobile. 

@ngk: please feel free to work your UX magic on the mock-up. And we'll be looking forward to Harlan's critique.

**Comment by 33eyes** [comment]
Hmm, the link to the mock-up may need to be this instead: https://moqups.com/ariiigu@gmail.com/Jvsyllrt

**Comment by 33eyes** [comment]
I got a quick critique on the mock-up above from a cognitive science UX expert. Her key points were the following:
- It might be a good idea to incorporate energy choice/switching somehow. Several states have deregulated their energy industries, and Massachusetts was the first to do it. There are lots of energy choice comparison tools out there, here's one: https://www.chooseenergy.com/massachusetts/cambridge/ 
- The sign-up should be much shorter, and joining the team should be either somewhere else or presented differently to the user. 
- Before and during early sign-up, user should see how much he/she could be saving on average by signing up. Same thing during later profile completion. For example, user could be informed of potential savings based on averages from existing users when they enter their zip code, or more specific savings estimates when they scan their bill. This will keep the user motivated to finish the sign-up.
- Need to be careful with achievement badges etc., because so many other apps have them nowadays. We need to think of our app as one out of an array of many apps the user interacts with. The badges are likely not a part of our minimally viable product, and thus it's better to leave them off for now if possible, and introduce them gradually later during user testing. If we do choose to use badges, we need to make sure they are not redundant to other elements. I guess there's some user fatigue associated with badges, and there are some better alternatives to them. 
- The team feature needs to be more prominent, and needs to be done in a way that does not put off people who don't want to join teams, if we intend to include them. And we need to make it obvious that joining a team is different (and a lot better) from simply connecting with friends.
- Lots of stuff needs to go from the dashboard mock-up, or at least be more intuitive.
- To make sure we get some initial users to sign up, we need to come up with clear personas, tailor the core design to target them, then expand/change features as needed with growth of user base.

**Comment by ngkristina** [comment]
Hey there, apologies for the delay—it's a bit more difficult to jump in mid project build than I thought it would be. I think I'll probably be more useful when I can actually chat with you all about the concept and the goals of the project. In the mean time, I agree with points above on simplifying and getting to the core of the user needs we're addressing. 

From what I get from reading through some of the presentations and issues, it sounds like we want to combine two different ideas:
—How can we use the power of peer pressure/rewards to reduce individual energy consumption?
—How can we take advantage of the 100 apartment building energy use dataset to do this?
Since one idea is not necessary to be successful in the other, I'm thinking this might be leading to feature bloat. But, each are very interesting windows into energy reduction on their own.

I'm a fan of these two simple frameworks when thinking about simple messages and focusing on motivating behavior change:
http://heathbrothers.com/download/switch-framework.pdf
http://heathbrothers.com/download/mts-made-to-stick-model.pdf

It sounds like there's a working prototype for some of the features, which would be a great place to start with validating some guesses as to what Cambridge residents can use/want. Looking forward to seeing more when I can come in :)

**Comment by mzagaja** [comment]
Closing this since we haven't acted on it in a long time. Though @ngkristina if you take a look at the app in its current state from the front page link we'd definitely love input on the portion where we provide the tips.
